### ISSUE TITLE
World Icons - Linux/MacOS Support

### ISSUE THREAD

**Issue by CommanderGL** [lamaprogramer/ReimaginedMenus#19]
When clicking on the `World Icons` button on Linux I get this error:
```
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.method_25426(WorldIconScreen.java:89) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.tabs.WorldTab.lambda$new$9(WorldTab.java:106) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 14 more
Caused by: java.nio.file.NoSuchFileException: /home/{COMPUTER_USERNAME}/.config/com.modrinth.theseus/profiles/Standard/worldicons\\GNG.png
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.Files.size(Unknown Source) ~[?:?]
	at net.iamaprogrammer.reimaginedmenus.gui.widgets.WorldIconListWidget$WorldIconEntry.<init>(WorldIconListWidget.java:90) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.lambda$updatePackList$2(WorldIconScreen.java:127) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.updatePackList(WorldIconScreen.java:122) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.updatePackLists(WorldIconScreen.java:112) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.refresh(WorldIconScreen.java:156) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.screen.WorldIconScreen.method_25426(WorldIconScreen.java:89) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1080) ~[client-intermediary.jar:?]
	at net.iamaprogrammer.reimaginedmenus.gui.tabs.WorldTab.lambda$new$9(WorldTab.java:106) ~[reimaginedmenus-1.1.0-1.20.x.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 14 more

```

The important part is: `java.nio.file.NoSuchFileException: /home/{COMPUTER_USERNAME}/.config/com.modrinth.theseus/profiles/Standard/worldicons\\icon.png`

**Comment by lamaprogramer** [comment]
Huh, Interesting, I'll see if I can figure it out, no promises though, as I don't own a Linux machine, I'll do my best though

**Comment by lamaprogramer** [comment]
Sorry it took me so long to get to this, but it should be fixed in the latest version now.

**Comment by CommanderGL** [comment]
thank you
